# 基于rating2inter.ipynb生成的5-core交互图，Train/Validation/Test data splitting
- Based on generated interactions, perform data splitting

In [1]:
import os, csv
import pandas as pd

In [2]:
!ls

0rating2inter.ipynb  2reindex-feat.ipynb  dualgnn-gen-u-u-matrix.py
1splitting.ipynb     3feat-encoder.ipynb  README.md

In [3]:
os.chdir('../data/grocery')
os.getcwd()

'/home/hun/MMRec_AlignRec/data/grocery'

## 直接加载现成的, Load interactions

In [4]:
rslt_file = 'grocery-indexed.inter'
df = pd.read_csv(rslt_file, sep='\t')
print(f'shape: {df.shape}')
df[:4]

shape: (151254, 5)

   userID  itemID  rating   timestamp  x_label
0       0       0     4.0  1370044800        0
1       2       0     4.0  1381190400        0
2       3       0     5.0  1369008000        0
3       4       0     4.0  1369526400        0

In [5]:
import random
import numpy as np

In [6]:

df = df.sample(frac=1).reset_index(drop=True)

df.sort_values(by=['userID'], inplace=True)
df[:20]

        userID  itemID  rating   timestamp  x_label
143879       0    7129     5.0  1391558400        1
21573        0    2204     3.0  1377820800        0
58185        0       0     4.0  1370044800        0
42402        0    4961     5.0  1345334400        0
114698       0    1115     5.0  1362700800        0
134711       0    6151     4.0  1373587200        0
62253        0     391     4.0  1356307200        0
72440        1    2485     5.0  1384905600        0
8054         1    7271     4.0  1355788800        0
146500       1     819     5.0  1367798400        0
137752       1    6600     3.0  1313107200        0
59032        1    5363     2.0  1301270400        0
80884        1    4913     5.0  1384905600        0
31534        1    5179     5.0  1361836800        0
12893        1       0     3.0  1400457600        2
56442        1    5290     5.0  1377820800        0
89963        1    5178     5.0  1369440000        0
139628       1    8498     4.0  1400112000        2
43889        1    4756     3.0  1260576000        0
132390       1    3533     5.0  1274572800        0

In [7]:
uid_field, iid_field = 'userID', 'itemID'

uid_freq = df.groupby(uid_field)[iid_field]
u_i_dict = {}
for u, u_ls in uid_freq:
    u_i_dict[u] = list(u_ls)
u_i_dict

{0: [7129, 2204, 0, 4961, 1115, 6151, 391],
 1: [2485,
  7271,
  819,
  6600,
  5363,
  4913,
  5179,
  0,
  5290,
  5178,
  8498,
  4756,
  3533,
  7024,
  5294,
  5015,
  7260,
  7489,
  8639,
  6191,
  3968,
  5292,
  3073,
  323,
  3343,
  3048],
 2: [6190, 2124, 6630, 193, 4430, 0],
 3: [6186, 0, 6450, 7266, 240, 8178, 7664, 5886],
 4: [7224, 2162, 5277, 0, 6571, 2004, 326],
 5: [0, 7821, 7625, 5341, 3685],
 6: [0, 323, 2313, 1266, 897, 3966],
 7: [3640, 7324, 1738, 6140, 0, 2060],
 8: [6403, 7632, 0, 5240, 5754],
 9: [5521, 8101, 4061, 236, 0, 5565, 6045],
 10: [5504, 577, 0, 4199, 5713, 2408, 5170],
 11: [2321, 493, 6322, 4807, 0],
 12: [4690, 0, 723, 7269, 1936, 1958, 3955, 1654, 1792, 4847, 5897, 8146],
 13: [4896, 858, 0, 2014, 4905],
 14: [6403, 1010, 3066, 1467, 1662, 0],
 15: [4353, 308, 3096, 4951, 0, 6879, 675, 921],
 16: [299, 6754, 7787, 3371, 1],
 17: [1974, 1936, 6737, 1, 1750, 437],
 18: [2094,
  775,
  6381,
  6356,
  687,
  7072,
  7152,
  7478,
  7175,
  968,
  1,
  7295,
  5277,
  2283,
  2437,
  3048,
  3154,
  2563,
  155],
 19: [1, 7594, 8535, 6679, 7426, 5017],
 20: [752,
  1,
  6921,
  840,
  3654,
  2000,
  8274,
  4147,
  842,
  6676,
  7018,
  844,
  4540,
  4863,
  8272,
  841],
 21: [1, 293, 142, 6633, 7503, 7180, 2310, 798],
 22: [4022, 1, 5016, 5568, 895],
 23: [6018, 204, 841, 840, 843, 1],
 24: [6130,
  4058,
  2443,
  1650,
  4641,
  1529,
  2954,
  7330,
  5313,
  5691,
  6763,
  2331,
  4423,
  6332,
  1242,
  2451,
  493,
  8517,
  6586,
  8311,
  2705,
  1470,
  8443,
  4936,
  7376,
  5138,
  8417,
  4191,
  4524,
  4837,
  7571,
  2697,
  5481,
  5104,
  7029,
  6976,
  8486,
  2367,
  4400,
  5830,
  8254,
  6354,
  1095,
  7964,
  3964,
  8118,
  2412,
  3432,
  8207,
  8076,
  6520,
  598,
  5765,
  5823,
  6997,
  1601,
  3755,
  4897,
  611,
  7766,
  6153,
  7265,
  6516,
  230,
  911,
  3715,
  7272,
  2611,
  1,
  7522,
  6162,
  8711,
  2599,
  2128,
  2210,
  3120,
  5363,
  6985,
  8583,
  8004,
  7738,
  7654,
  4778,
  6815,
  7898,
  4832,
  8497,
  7317,
  2433,
  3319,
  4765,
  4540,
  4766,
  7612,
  3707,
  6331,
  8267],
 25: [1, 1112, 3201, 6716, 7195],
 26: [2466, 1, 5633, 3680, 5412, 4286, 1373, 5453, 5966, 840],
 27: [2218, 2885, 2268, 1, 939],
 28: [844, 1498, 1, 1285, 840, 666, 1111],
 29: [844,
  4286,
  842,
  7673,
  1987,
  4264,
  5149,
  142,
  4144,
  4293,
  1758,
  1,
  840,
  3160,
  4275,
  4269,
  4272],
 30: [1, 4745, 840, 4618, 842],
 31: [6653,
  5516,
  4709,
  3444,
  493,
  920,
  4451,
  7125,
  2,
  4668,
  7198,
  2026,
  4240,
  4290,
  5017,
  140,
  4136],
 32: [6945, 1964, 769, 747, 1600, 2],
 33: [920, 1834, 2868, 2, 921],
 34: [573,
  7448,
  2,
  5230,
  160,
  1065,
  8391,
  2414,
  7051,
  18,
  120,
  7835,
  593,
  121,
  7910,
  212,
  325],
 35: [4810, 6424, 4550, 487, 7773, 7029, 6815, 371, 2, 368],
 36: [6286, 6623, 2, 2816, 7155],
 37: [5743, 2, 5918, 3284, 5886, 5488, 7664, 7264, 1835, 5672],
 38: [3, 4101, 911, 3880, 8416, 8234, 4984, 608, 1710, 4576, 6524, 6673, 3574],
 39: [8548,
  6230,
  1764,
  338,
  4096,
  7860,
  2008,
  1027,
  498,
  4887,
  1808,
  5323,
  7828,
  4368,
  6006,
  3767,
  2388,
  1023,
  266,
  8613,
  4674,
  7219,
  7524,
  6897,
  3,
  1466],
 40: [2180,
  574,
  5596,
  2563,
  7772,
  2212,
  5117,
  4190,
  7311,
  5693,
  5691,
  3300,
  2934,
  3492,
  7639,
  5807,
  837,
  5122,
  1565,
  2192,
  6358,
  4510,
  2138,
  4402,
  1742,
  6020,
  5198,
  905,
  1433,
  3],
 41: [2544,
  6141,
  3051,
  3909,
  2541,
  7957,
  3686,
  6041,
  3303,
  1982,
  1344,
  2543,
  893,
  6976,
  2545,
  5293,
  5111,
  2300,
  4768,
  2039,
  3,
  4602,
  3925,
  2851,
  4517,
  470,
  2395,
  2542,
  3305,
  2031,
  210,
  3471,
  8490,
  3125,
  5292,
  5951,
  1983,
  6772,
  6180,
  5167,
  6924,
  334,
  6625,
  4823,
  2316,
  7702,
  6058,
  1987,
  4550,
  5086,
  7958,
  3053,
  4645,
  897,
  8050,
  7294,
  5290,
  3058,
  1709,
  3685,
  7960,
  663,
  6297,
  2681,
  895,
  5247,
  680,
  816,
  2850,
  5618,
  2706,
  5294,
  886,
  4655,
  265,
  610,
  2981,
  3683,
  3106,
  1333,
  302,
  2155,
  7481,
  6044,
  7273,
  6390,
  7625,
  3019,
  3341,
  2985,
  40,
  332,
  6052,
  3484,
  593,
  699,
  8295,
  7673,
  4476,
  10,
  5950,
  4371],
 42: [1177, 3250, 3284, 3727, 2623, 3, 254, 7143, 1379, 3405, 3395, 3961, 178],
 43: [2414,
  3199,
  5998,
  4096,
  8018,
  473,
  5953,
  5763,
  4427,
  6092,
  5823,
  5824,
  7432,
  6163,
  3,
  1520,
  307,
  6205,
  5481,
  6153,
  531,
  508,
  715,
  7688,
  7043,
  6821,
  5540,
  5611,
  4850,
  8535,
  5693,
  6774,
  7766,
  310,
  7215,
  6192,
  5343,
  5138,
  911,
  6340,
  6134,
  6224,
  5610,
  6793,
  6912,
  6773],
 44: [3595, 1087, 2735, 3, 6318, 3596, 6179, 3891],
 45: [2001, 348, 6486, 597, 5872, 3, 1443, 4951, 7353, 3101],
 46: [4532, 8087, 2044, 5534, 1950, 5695, 3],
 47: [677,
  3388,
  674,
  6252,
  2128,
  4,
  508,
  3199,
  1895,
  686,
  4132,
  1907,
  5356,
  366,
  2821,
  1493,
  488,
  3590,
  2588,
  2661,
  5805,
  575,
  693,
  1958,
  1567,
  3586,
  1859,
  574,
  4612,
  4610,
  2121,
  669,
  663,
  1399,
  2399,
  1398,
  3223,
  2353,
  3434,
  1482,
  4036,
  578,
  185,
  1505,
  1340,
  573,
  483,
  2741,
  2622,
  706,
  3746],
 48: [4, 689, 5972, 482, 4324],
 49: [3927, 359, 6119, 173, 4, 6872, 354],
 50: [5516, 4, 348, 2683, 7298, 2599, 6345],
 51: [8302, 7860, 3250, 4, 2827, 1784, 1181],
 52: [5022, 6095, 6928, 4095, 1535, 4, 5757],
 53: [2438,
  2317,
  4,
  1167,
  359,
  3270,
  4470,
  5781,
  3176,
  8361,
  6429,
  5819,
  3144,
  3192],
 54: [5,
  849,
  1480,
  2704,
  3410,
  1411,
  2802,
  5733,
  5017,
  2434,
  2981,
  2149,
  5645],
 55: [8691,
  4509,
  3599,
  197,
  469,
  4026,
  6319,
  544,
  5172,
  3595,
  3596,
  2735,
  1242,
  8498,
  17,
  162,
  4897,
  5,
  1431],
 56: [5426,
  4778,
  5953,
  4423,
  4539,
  3438,
  1257,
  980,
  8000,
  3854,
  4871,
  7889,
  3540,
  8155,
  1015,
  8547,
  3917,
  4422,
  4486,
  8675,
  8154,
  8484,
  7804,
  7862,
  3159,
  5,
  1086,
  6367,
  3166,
  5067,
  887,
  5596,
  711,
  8267,
  3146,
  3017,
  1008,
  5343,
  8127,
  5890,
  494,
  8543,
  1036,
  1003,
  8546,
  5153,
  8293,
  2542,
  5830,
  7121,
  5743,
  2563,
  585,
  7579,
  8645,
  6404,
  8190,
  8535,
  4261,
  5112,
  7948,
  7618,
  1009,
  7949,
  8519,
  7608,
  532,
  8508,
  5824,
  8305,
  7556,
  7296,
  5370,
  7432,
  6447],
 57: [7603, 2711, 4509, 5, 2697, 2713],
 58: [286,
  8207,
  4423,
  522,
  884,
  3121,
  5,
  923,
  6367,
  334,
  7116,
  3816,
  4778,
  1467,
  6434,
  921,
  8293,
  2041],
 59: [1467,
  6307,
  3071,
  3713,
  7575,
  2133,
  5,
  2484,
  8513,
  3051,
  3685,
  6088,
  4013,
  4437,
  2518,
  8701,
  3068,
  6586,
  7603,
  4094,
  6288,
  5341,
  2438,
  2745,
  307,
  8295,
  1083,
  1130,
  6617,
  4186,
  4551,
  1152,
  3708,
  7375,
  701,
  2676,
  3453,
  2876,
  242,
  5292,
  2577,
  663,
  6805,
  5904,
  3956,
  6058,
  4100,
  1442,
  4023,
  6524,
  3188,
  6056,
  5907,
  5257,
  706,
  8120],
 60: [6512,
  3497,
  8261,
  6177,
  6814,
  6815,
  5353,
  1599,
  3541,
  1005,
  5293,
  2044,
  1467,
  598,
  6,
  8214,
  8213,
  6340,
  7380,
  6522,
  2717,
  4089],
 61: [473, 1826, 4321, 6, 5973, 4322, 8432],
 62: [7301, 3040, 7891, 6, 6975],
 63: [4550, 7309, 3051, 4378, 4354, 6, 4552, 5565],
 64: [6, 2753, 3045, 5100, 6829, 6349],
 65: [6, 804, 151, 5467, 3656, 4363, 5572, 4212, 6086, 5468],
 66: [7798, 2493, 5937, 6, 3654],
 67: [682,
  3312,
  5513,
  6569,
  2588,
  5731,
  203,
  665,
  5005,
  7,
  8545,
  3779,
  3187,
  8560,
  7608,
  5620,
  2790,
  3682,
  3227,
  1344,
  8144,
  2545,
  1458,
  3454,
  2028,
  8661,
  5004],
 68: [4644, 2882, 3619, 7, 1088, 580, 4143, 1694, 1220],
 69: [7971,
  8122,
  8645,
  6404,
  7653,
  4024,
  5354,
  6815,
  6154,
  7556,
  4932,
  7979,
  7277,
  8643,
  8475,
  7608,
  7,
  8509,
  7432,
  8546,
  6204,
  5953,
  8504,
  6205,
  3118,
  8644,
  7816,
  8543,
  610,
  8325,
  5577,
  6590,
  54,
  6192,
  7299,
  7298,
  7655,
  8417,
  8474],
 70: [902,
  6586,
  8207,
  4833,
  2676,
  4778,
  8293,
  3963,
  3746,
  7299,
  3816,
  3233,
  8504,
  6922,
  7272,
  6520,
  6154,
  2666,
  8081,
  7,
  3961,
  6562,
  7608,
  1242,
  7215,
  1151,
  3826,
  8496,
  8502,
  6815,
  2530,
  5062,
  8493,
  7655,
  6836,
  7123,
  4926],
 71: [7, 6009, 8323, 6478, 5112],
 72: [1686,
  2363,
  539,
  586,
  3880,
  4451,
  2570,
  2367,
  2783,
  4270,
  913,
  7,
  903,
  5914,
  4312,
  3608,
  3856],
 73: [7, 1936, 3431, 6746, 7117],
 74: [1252, 2830, 2831, 172, 2825, 7, 5033, 5317],
 75: [6429, 8018, 835, 8, 7151, 6728, 3189, 7035, 625, 6850, 2378],
 76: [8199, 1216, 1474, 2466, 6271, 6304, 8, 6301, 2931, 187, 8009],
 77: [4801,
  4754,
  1797,
  2764,
  2395,
  5172,
  6209,
  4900,
  1651,
  8513,
  8554,
  797,
  8497,
  8627,
  2155,
  2978,
  6669,
  6819,
  3959,
  981,
  1546,
  157,
  5102,
  3819,
  517,
  5662,
  2008,
  1720,
  4867,
  82,
  1570,
  2480,
  3501,
  4895,
  4901,
  4894,
  3860,
  5278,
  5376,
  8,
  518,
  3803,
  5550,
  2100,
  273,
  1719,
  2276,
  2700,
  1245,
  2769,
  238,
  218,
  5319,
  1551,
  947,
  6097,
  2905,
  7860,
  3770,
  991,
  1013,
  7391,
  3522,
  2639,
  883,
  4462,
  3767,
  3107,
  2402,
  519,
  5377,
  1981,
  3820,
  7582,
  3460,
  3523,
  3870,
  2952,
  2073,
  5561,
  6818,
  2162,
  6218,
  2763,
  3409,
  8488],
 78: [24,
  3881,
  5605,
  663,
  6601,
  1433,
  519,
  5668,
  1333,
  6340,
  517,
  7432,
  3964,
  1334,
  7571,
  1242,
  2583,
  8527,
  360,
  3963,
  5824,
  7300,
  3841,
  7143,
  8008,
  4628,
  1431,
  6320,
  479,
  6154,
  6569,
  7272,
  236,
  664,
  3267,
  670,
  518,
  8,
  5998,
  7329],
 79: [3709,
  3525,
  2658,
  1260,
  3237,
  4354,
  8,
  2766,
  6356,
  4678,
  6252,
  1259,
  58,
  4036],
 80: [8, 6665, 6096, 5686, 802, 7347],
 81: [7750, 2777, 7310, 7711, 5277, 8],
 82: [6009,
  175,
  505,
  5463,
  5093,
  8,
  1649,
  6075,
  7860,
  1780,
  8016,
  902,
  3903,
  1112],
 83: [2234, 9, 4095, 1878, 800],
 84: [1060, 387, 941, 2563, 9],
 85: [9, 669, 840, 322, 7218, 1670, 726],
 86: [5277, 2441, 663, 9, 5602],
 87: [9, 7001, 4212, 2407, 3610],
 88: [5859, 2638, 42, 6345, 1024, 342, 10],
 89: [1044, 267, 10, 607, 4535, 252, 3512, 1333, 3190],
 90: [5954, 10, 6335, 6934, 5483, 7343, 7344, 8106, 4691],
 91: [4960, 4371, 5572, 8119, 3819, 6378, 10, 7559],
 92: [6564, 4075, 96, 5022, 1474, 1374, 7164, 2886, 11, 294, 5722, 1635, 6515],
 93: [4989,
  4020,
  2814,
  3453,
  4812,
  7655,
  5113,
  4550,
  4488,
  5403,
  1627,
  275,
  4567,
  3020,
  3058,
  5437,
  6304,
  3786,
  4028,
  4548,
  3033,
  5340,
  6045,
  3511,
  5086,
  7446,
  5194,
  5431,
  3051,
  4566,
  5565,
  6872,
  3897,
  1297,
  7346,
  3053,
  4569,
  3346,
  7653,
  3823,
  6393,
  2204,
  11,
  3824,
  6391,
  3015,
  7889,
  4549,
  4461,
  3018,
  3065,
  4552,
  3026,
  648,
  4024],
 94: [11, 1458, 5516, 4690, 2409, 4425],
 95: [3197, 230, 11, 3371, 3500, 65],
 96: [5772, 3727, 3916, 1884, 1960, 1413, 11, 4223],
 97: [3711, 7744, 12, 5539, 5074],
 98: [12, 4621, 611, 4101, 6851],
 99: [7316, 12, 465, 6168, 5628, 6170],
 100: [2323,
  5953,
  2216,
  3490,
  8331,
  4423,
  7121,
  8655,
  4778,
  12,
  7296,
  1481,
  990,
  3084,
  4896,
  4414,
  8170,
  4899,
  5830],
 101: [12,
  7291,
  5276,
  7292,
  7753,
  7346,
  7369,
  1635,
  8005,
  5041,
  4448,
  7294,
  4552,
  5239,
  593],
 102: [330,
  5570,
  251,
  1366,
  4485,
  2704,
  5395,
  7944,
  4324,
  7374,
  8189,
  611,
  2884,
  4939,
  4082,
  4390,
  2905,
  938,
  1402,
  6372,
  7180,
  2937,
  4666,
  799,
  1811,
  7263,
  1118,
  7145,
  2675,
  1244,
  2187,
  5953,
  3048,
  4252,
  6207,
  6802,
  1649,
  5499,
  807,
  5428,
  7260,
  493,
  6111,
  7577,
  4786,
  7516,
  1352,
  5680,
  5848,
  5533,
  5394,
  3040,
  4201,
  4434,
  1612,
  3883,
  6886,
  7583,
  3099,
  5369,
  5999,
  4224,
  7457,
  1696,
  2480,
  4785,
  4405,
  6805,
  6138,
  6808,
  546,
  1760,
  1421,
  2825,
  8206,
  6406,
  7782,
  6831,
  1657,
  8393,
  6164,
  1451,
  3067,
  1545,
  1117,
  2827,
  7803,
  1893,
  5594,
  2420,
  7064,
  1417,
  2438,
  8132,
  6917,
  1423,
  7462,
  5364,
  5995,
  5846,
  6887,
  2436,
  1597,
  7601,
  4753,
  1949,
  7303,
  6174,
  2828,
  5173,
  2622,
  6918,
  5343,
  4890,
  6804,
  4004,
  1890,
  7459,
  4696,
  804,
  3891,
  4227,
  5988,
  329,
  601,
  5027,
  4704,
  4021,
  2826,
  4078,
  421,
  4514,
  5029,
  5107,
  3640,
  323,
  2095,
  2068,
  6485,
  7579,
  420,
  6285,
  6039,
  1416,
  1853,
  5481,
  1092,
  4245,
  4515,
  1407,
  1446,
  6381,
  6091,
  7866,
  6127,
  5963,
  4887,
  6783,
  4674,
  6966,
  7955,
  7181,
  13,
  1131,
  2180,
  8468,
  5865,
  5932,
  6197,
  4646,
  798,
  8107,
  1119,
  2346,
  6241,
  61,
  3770,
  6206,
  3414,
  1854],
 103: [13, 5040, 3396, 1564, 920],
 104: [567, 1701, 5122, 552, 7515, 13, 3048],
 105: [8427,
  3037,
  1172,
  1751,
  2079,
  1106,
  2046,
  4728,
  3523,
  14,
  1743,
  3267,
  6160,
  1169,
  2541,
  1597,
  3358,
  13,
  4766,
  4635,
  990,
  3009,
  1744,
  3516,
  1453,
  5125],
 106: [5022, 4632, 13, 7507, 3627],
 107: [2438, 13, 689, 874, 518, 1470, 940],
 108: [13, 3096, 5350, 3516, 3208, 7671],
 109: [5846, 14, 3905, 3816, 2676, 2046],
 110: [305, 7397, 5073, 4155, 3201, 8037, 14],
 111: [5620, 911, 14, 5449, 2046, 7553],
 112: [8505,
  4448,
  8293,
  6047,
  5406,
  8547,
  7771,
  2009,
  8519,
  5904,
  7188,
  8502,
  5393,
  4696,
  4778,
  8509,
  8506,
  1828,
  867,
  8520,
  4849,
  6997,
  7200,
  1561,
  6045,
  4848,
  4423,
  7210,
  7290,
  4255,
  4896,
  4693,
  4925,
  8527,
  4641,
  7331,
  8000,
  8165,
  7223,
  8210,
  1569,
  8500,
  6034,
  14,
  7437,
  8504,
  8515,
  1911,
  3465,
  5830,
  5043],
 113: [8213,
  8352,
  4926,
  7892,
  6340,
  4641,
  4833,
  6331,
  4423,
  3755,
  5354,
  6586,
  6344,
  1087,
  884,
  3746,
  6233,
  3693,
  8486,
  222,
  4092,
  8000,
  4660,
  1433,
  6179,
  1242,
  245,
  880,
  7331,
  6991,
  8293,
  8561,
  2653,
  8533,
  8493,
  1113,
  8261,
  900,
  6236,
  4089,
  8531,
  7332,
  7330,
  6153,
  6232,
  2406,
  8206,
  5765,
  7333,
  7893,
  6235,
  8346,
  8443,
  7607,
  2446,
  8682,
  7299,
  8632,
  7571,
  2139,
  8190,
  6367,
  7329,
  902,
  14,
  8215,
  2564,
  8353,
  4400,
  8534,
  6332,
  1431,
  7143,
  1128,
  7298,
  4778,
  7272,
  2735,
  5693,
  8122,
  7816],
 114: [8480,
  4361,
  275,
  109,
  2474,
  14,
  4938,
  7665,
  5866,
  2550,
  4648,
  3902,
  5504,
  4425,
  587,
  5021,
  7780,
  790,
  4712,
  7940,
  2608,
  6745,
  5623,
  8610,
  5189,
  2138,
  4727,
  4101,
  4175,
  349,
  2690,
  2904,
  5988,
  3067,
  721,
  7060,
  7089,
  583,
  2019,
  913,
  4034,
  8031,
  3266,
  6769,
  6517,
  2372,
  2139,
  6302,
  5783,
  307,
  4300,
  798,
  594,
  6721,
  7910,
  4404,
  7434,
  7273,
  3663,
  1424,
  2563,
  5831,
  5979,
  1111,
  2290,
  6675,
  725,
  3358,
  723,
  2985,
  2652,
  716,
  4058,
  6470,
  4223,
  4410,
  1548],
 115: [15,
  4074,
  4445,
  4056,
  5017,
  2759,
  4439,
  3508,
  5021,
  3846,
  8011,
  2563,
  6844],
 116: [4800, 4801, 15, 4284, 2748],
 117: [1992, 4246, 5691, 4878, 5117, 5733, 4067, 4191, 15],
 118: [4381,
  7014,
  4842,
  7265,
  8519,
  7556,
  8520,
  8215,
  8213,
  8000,
  141,
  8306,
  6608,
  8155,
  2041,
  5105,
  8417,
  8467,
  2057,
  8543,
  8561,
  8545,
  8267,
  3106,
  7903,
  6953,
  4423,
  8544,
  8154,
  8443,
  8190,
  8305,
  8214,
  8547,
  8156,
  7981,
  7955,
  4766,
  6256,
  3756,
  8165,
  8405,
  8515,
  8470,
  723,
  15,
  5320,
  8404,
  4778,
  7816,
  1184],
 119: [4991,
  294,
  5357,
  2197,
  2015,
  84,
  15,
  389,
  2016,
  16,
  8238,
  2216,
  4170,
  3594,
  5314],
 120: [1889, 2371, 308, 310, 1453, 3194, 3188, 849, 15, 1443, 827, 585],
 121: [3613, 5178, 6409, 4524, 15],
 122: [7331,
  5685,
  2677,
  1991,
  4094,
  3239,
  901,
  7380,
  2526,
  584,
  8677,
  7029,
  15,
  7687,
  707,
  7382,
  1709,
  4423,
  7144,
  3816,
  1668,
  601,
  1217,
  7377,
  8030,
  1807,
  6512,
  1149,
  6815,
  407,
  7522,
  1574,
  4092,
  4026,
  774,
  599,
  3540],
 123: [3371, 15, 2753, 3894, 7188],
 124: [5668, 7330, 8535, 8000, 5531, 4376, 15, 5535],
 125: [6586,
  4324,
  5149,
  7162,
  6903,
  8498,
  8495,
  4423,
  6562,
  15,
  4778,
  4622,
  6340,
  6208,
  370,
  8532,
  2487,
  351,
  8293,
  2313,
  8711,
  6205,
  7816,
  5691,
  5245,
  5882,
  1433,
  8645,
  5605,
  8709],
 126: [3792, 4134, 4791, 3048, 1506, 15, 2354],
 127: [589,
  3707,
  2476,
  5877,
  6141,
  847,
  7693,
  707,
  730,
  5021,
  5800,
  851,
  588,
  7428,
  6219,
  7234,
  5892,
  5152,
  6144,
  5789,
  6326,
  272,
  6444,
  5002,
  15,
  2044,
  7164,
  5782,
  6090,
  4197,
  1366,
  3709,
  6680,
  1130,
  7422,
  4766,
  5521,
  6729,
  1247,
  5169,
  1904,
  4907,
  8429,
  8076,
  889,
  2846,
  4477,
  8117],
 128: [2425, 16, 4113, 6066, 2412],
 129: [4651, 510, 1601, 6851, 16, 6476, 6157],
 130: [5409,
  5645,
  6900,
  5701,
  5682,
  7742,
  7345,
  2132,
  5188,
  5286,
  2979,
  1768,
  7823,
  16],
 131: [140,
  3764,
  7665,
  6900,
  16,
  6341,
  4359,
  7709,
  4087,
  5100,
  6712,
  2752,
  4073,
  5736,
  1936],
 132: [8334,
  6101,
  1065,
  4026,
  8293,
  6232,
  7687,
  5668,
  6236,
  6332,
  7228,
  7121,
  17,
  6344,
  8336,
  8000],
 133: [8535,
  8639,
  2735,
  7765,
  6872,
  8498,
  8165,
  8667,
  4892,
  3728,
  8710,
  6985,
  3016,
  7979,
  3923,
  5685,
  8496,
  7889,
  4926,
  17,
  3595,
  6460],
 134: [7812, 5285, 4236, 2495, 17, 2675],
 135: [2598, 5848, 5841, 7019, 17],
 136: [63, 7921, 5516, 7479, 7352, 7213, 8123, 17, 362],
 137: [5096,
  7796,
  7291,
  8052,
  7514,
  2726,
  2751,
  819,
  4022,
  8018,
  6801,
  3449,
  5655,
  2002,
  34,
  2503,
  6798,
  1045,
  18,
  7581,
  3923,
  5575,
  5325,
  3686,
  7420,
  7889,
  3481,
  7460,
  6306,
  211,
  4882,
  204,
  3795,
  5481,
  3618,
  7463,
  7308,
  2228,
  2504,
  7448,
  6919,
  7263,
  5926,
  7309,
  6096],
 138: [4342, 216, 91, 41, 18],
 139: [7882,
  6164,
  1482,
  1095,
  1489,
  596,
  2973,
  2853,
  600,
  7298,
  2926,
  1428,
  251,
  18,
  1437],
 140: [7508,
  3917,
  7101,
  5324,
  6137,
  3411,
  5563,
  7737,
  204,
  7009,
  161,
  2539,
  6780,
  7674,
  5557,
  7802,
  2281,
  8203,
  1564,
  35,
  232,
  7118,
  3769,
  7672,
  1650,
  5082,
  1226,
  480,
  1544,
  253,
  7008,
  3820,
  8009,
  4051,
  2206,
  7974,
  4419,
  1989,
  18,
  8710,
  3621,
  4251,
  245,
  8653,
  233,
  7445,
  4588,
  2130,
  3761,
  7671,
  3702,
  6501,
  3953,
  5902,
  3900,
  5601,
  6844,
  1669,
  4786,
  8287,
  1474,
  7673,
  2207,
  5230,
  4385,
  110,
  2604,
  6256,
  1305],
 141: [1067,
  1101,
  19,
  859,
  4831,
  4170,
  918,
  4262,
  821,
  545,
  633,
  7409,
  4900,
  4749,
  3271,
  7756,
  2012,
  4740],
 142: [7049, 19, 2530, 6903, 1242],
 143: [5708, 7629, 7155, 19, 4550, 4096, 7291, 5052],
 144: [593, 4552, 6053, 3058, 19, 7220, 6583],
 145: [3349, 124, 2646, 3048, 3619, 4293, 3749, 19],
 146: [5900,
  874,
  573,
  8259,
  4500,
  7752,
  2113,
  6675,
  275,
  26,
  5318,
  5576,
  4489,
  4151,
  348,
  5322,
  5138,
  4541,
  6380,
  4965,
  3458,
  5560,
  204,
  7427,
  4191,
  2705,
  92,
  4419,
  6510,
  843,
  598,
  1217,
  19,
  6207,
  230,
  124,
  5139,
  2228,
  7629,
  8258],
 147: [3832, 721, 3745, 2984, 19, 1713, 718, 4983, 3166],
 148: [6610,
  5465,
  1392,
  5681,
  1717,
  1499,
  3449,
  5897,
  5734,
  7306,
  2771,
  1313,
  6611,
  578,
  2949,
  19,
  585,
  2940,
  1512,
  7231,
  3886,
  1172,
  6498,
  5896,
  333,
  5988,
  2128],
 149: [1350,
  4075,
  6356,
  3009,
  3926,
  7713,
  4116,
  5667,
  3629,
  19,
  6139,
  1877,
  44],
 150: [7556,
  5062,
  5721,
  8648,
  3101,
  6205,
  7296,
  7272,
  6903,
  8417,
  19,
  8267,
  7766,
  4026,

In [8]:
new_label = []
u_ids_sorted = sorted(u_i_dict.keys())

for u in u_ids_sorted:
    items = u_i_dict[u]
    n_items = len(items)
    if n_items < 10:
        tmp_ls = [0] * (n_items - 2) + [1] + [2]
    else:
        val_test_len = int(n_items * 0.2)
        train_len = n_items - val_test_len
        val_len = val_test_len // 2
        test_len = val_test_len - val_len
        tmp_ls = [0] * train_len + [1] * val_len + [2] * test_len
    new_label.extend(tmp_ls)

new_label[:100]

[0,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0]

In [9]:
df['x_label'] = new_label
df[:20]

        userID  itemID  rating   timestamp  x_label
143879       0    7129     5.0  1391558400        0
21573        0    2204     3.0  1377820800        0
58185        0       0     4.0  1370044800        0
42402        0    4961     5.0  1345334400        0
114698       0    1115     5.0  1362700800        0
134711       0    6151     4.0  1373587200        1
62253        0     391     4.0  1356307200        2
72440        1    2485     5.0  1384905600        0
8054         1    7271     4.0  1355788800        0
146500       1     819     5.0  1367798400        0
137752       1    6600     3.0  1313107200        0
59032        1    5363     2.0  1301270400        0
80884        1    4913     5.0  1384905600        0
31534        1    5179     5.0  1361836800        0
12893        1       0     3.0  1400457600        0
56442        1    5290     5.0  1377820800        0
89963        1    5178     5.0  1369440000        0
139628       1    8498     4.0  1400112000        0
43889        1    4756     3.0  1260576000        0
132390       1    3533     5.0  1274572800        0

In [10]:
rslt_file[:-6]

'grocery-indexed'

In [11]:
new_labeled_file = rslt_file[:-6] + '-v4.inter'
df.to_csv(os.path.join('./', new_labeled_file), sep='\t', index=False)
print('done!!!')

done!!!

## Reload

In [12]:
indexed_df = pd.read_csv(new_labeled_file, sep='\t')
print(f'shape: {indexed_df.shape}')
indexed_df[:20]

shape: (151254, 5)

    userID  itemID  rating   timestamp  x_label
0        0    7129     5.0  1391558400        0
1        0    2204     3.0  1377820800        0
2        0       0     4.0  1370044800        0
3        0    4961     5.0  1345334400        0
4        0    1115     5.0  1362700800        0
5        0    6151     4.0  1373587200        1
6        0     391     4.0  1356307200        2
7        1    2485     5.0  1384905600        0
8        1    7271     4.0  1355788800        0
9        1     819     5.0  1367798400        0
10       1    6600     3.0  1313107200        0
11       1    5363     2.0  1301270400        0
12       1    4913     5.0  1384905600        0
13       1    5179     5.0  1361836800        0
14       1       0     3.0  1400457600        0
15       1    5290     5.0  1377820800        0
16       1    5178     5.0  1369440000        0
17       1    8498     4.0  1400112000        0
18       1    4756     3.0  1260576000        0
19       1    3533     5.0  1274572800        0

In [13]:
u_id_str, i_id_str = 'userID', 'itemID'
u_uni = indexed_df[u_id_str].unique()
c_uni = indexed_df[i_id_str].unique()

print(f'# of unique learners: {len(u_uni)}')
print(f'# of unique courses: {len(c_uni)}')

print('min/max of unique learners: {0}/{1}'.format(min(u_uni), max(u_uni)))
print('min/max of unique courses: {0}/{1}'.format(min(c_uni), max(c_uni)))

# of unique learners: 14681
# of unique courses: 8713
min/max of unique learners: 0/14680
min/max of unique courses: 0/8712